# Generated by Django 5.2.15 on 2026-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='blogs',
            name='Status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'published')], default='DR', max_length=10),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['-publish'], name='blogs_blogs_publish_dfdb1a_idx'),
        ),
    ]
